name: Tester

on:
  push:
    branches:
      - main
      - frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          cd my-app/my-app
          yarn install
      - name: Build application
        run: |
          yarn build
