name: Tester

on:
  push:
    branches:
      - main
      - frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: my-app
        run: yarn install
      - name: Build application
        working-directory: my-app
        run: yarn build
